version: '3.8'

services:
  server-a-vesa:
    build:
      context: ./server-a
    volumes:
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    networks:
      - app-network
  server-b-vesa:
    build:
      context: ./server-b
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
