version: '3.8'
services:
  server-a-vesa:
    image: server-a-image
    build: ./server-a
    depends_on:
      - rabbitmq-vesa

  server-b-vesa:
    image: server-b-image
    build: ./server-b
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq-vesa

  monitor-vesa:
    image: monitor-image
    build: ./monitor
    ports:
      - "8087:8087"
    depends_on:
      - rabbitmq-vesa

  rabbitmq-vesa:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
