version: '3.8'

services:
  server-a:
    build:
      context: ./server-a
    volumes:
      - /var/logs/:/var/logs/
    ports:
      - "3000:3000"
    networks:
      - app-network
  server-b:
    build:
      context: ./server-b
    volumes:
      - /var/logs/:/var/logs/
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
