# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservice2.proto\"\x1f\n\x0c\x43ountRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x36\n\x08Service2\x12*\n\tCountZero\x12\r.CountRequest\x1a\x0e.CountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COUNTREQUEST']._serialized_start=18
  _globals['_COUNTREQUEST']._serialized_end=49
  _globals['_COUNTRESPONSE']._serialized_start=51
  _globals['_COUNTRESPONSE']._serialized_end=81
  _globals['_SERVICE2']._serialized_start=83
  _globals['_SERVICE2']._serialized_end=137
# @@protoc_insertion_point(module_scope)
