# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service2_pb2 as service2__pb2


class Service2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountZero = channel.unary_unary(
                '/Service2/CountZero',
                request_serializer=service2__pb2.CountRequest.SerializeToString,
                response_deserializer=service2__pb2.CountResponse.FromString,
                )


class Service2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountZero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Service2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountZero': grpc.unary_unary_rpc_method_handler(
                    servicer.CountZero,
                    request_deserializer=service2__pb2.CountRequest.FromString,
                    response_serializer=service2__pb2.CountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service2/CountZero',
            service2__pb2.CountRequest.SerializeToString,
            service2__pb2.CountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
